// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA89Q3kHWm31eW-TmqGDudG9IEhtXGgSZY',
    appId: '1:1020225147222:web:399ac3842ecd3789db06f7',
    messagingSenderId: '1020225147222',
    projectId: 'musclemetrics-f9995',
    authDomain: 'musclemetrics-f9995.firebaseapp.com',
    storageBucket: 'musclemetrics-f9995.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuZ6TVIP5PaInms4uUhJM5YrtS9hVvzVY',
    appId: '1:1020225147222:android:12a4ee387ba01203db06f7',
    messagingSenderId: '1020225147222',
    projectId: 'musclemetrics-f9995',
    storageBucket: 'musclemetrics-f9995.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyoTdzwWU-H6sXWbDooEuCxeWZtySvTjY',
    appId: '1:1020225147222:ios:67f22cb888aa4980db06f7',
    messagingSenderId: '1020225147222',
    projectId: 'musclemetrics-f9995',
    storageBucket: 'musclemetrics-f9995.appspot.com',
    iosBundleId: 'com.example.gymTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyoTdzwWU-H6sXWbDooEuCxeWZtySvTjY',
    appId: '1:1020225147222:ios:67f22cb888aa4980db06f7',
    messagingSenderId: '1020225147222',
    projectId: 'musclemetrics-f9995',
    storageBucket: 'musclemetrics-f9995.appspot.com',
    iosBundleId: 'com.example.gymTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA89Q3kHWm31eW-TmqGDudG9IEhtXGgSZY',
    appId: '1:1020225147222:web:4613e6e7bf9381e4db06f7',
    messagingSenderId: '1020225147222',
    projectId: 'musclemetrics-f9995',
    authDomain: 'musclemetrics-f9995.firebaseapp.com',
    storageBucket: 'musclemetrics-f9995.appspot.com',
  );
}
